### ISSUE TITLE
Implementation of F_s_odd and F_s_even in the SciBlock class

### ISSUE THREAD

**Issue by rnjbdya** [Meatssauce/SCINet#1]
I am not sure if this changes much but I am guessing the codes for F_s_odd and F_s_even should be something like below:
.............................

F_s_odd = F_odd * tf.math.exp(phi(F_even))
F_s_even = F_even * tf.math.exp(psi(F_odd))

.............................

Also, can you show the results you got with this implementation?

**Comment by Meatssauce** [comment]
No, you need to pass each tensor through their corresponding convolution module before multiplying them element-wise with each other to achieve interactive learning.

These are the original equations from the paper:

F_s_odd = F_odd * exp(φ(F_even)) 
F_s_even = F_even * exp(ψ(F_odd))

where φ and ψ are two conv1d modules in a SCIBlock.
self.conv1ds['phi'] is a composite layer so it wouldn't make sense to pass it to tf.math.exp anyway.

I ran the latest version on ETTh1 with horizon = 24, using the hyperparameters listed in the paper and got 
mse = 0.889, mae = 0.686. The results in the paper were mse = 0.311 and mae = 0.348.

You can see that my results are a bit higher than the original. However, the authors didn't say anything about regularization and I haven't done any tuning on that yet so I can't say if it's caused by a mistake in my implementation.

**Comment by rnjbdya** [comment]
Actually, I made a mistake in my previous comment. What I was trying to say is, in your code you have passed 'F_s_odd' to the 'ψ' convolution block instead of 'F_odd'.

In your code:
F_s_even = F_even * exp(ψ(F_s_odd))

What it should be:
F_s_even = F_even * exp(ψ(F_odd))

**Comment by Meatssauce** [comment]
Ah I see. Thanks for that. 

I have pushed an update.
